# Generated by Django 3.0.8 on 2020-07-05 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('idDocumento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=50)),
                ('documento', models.FileField(upload_to='apempresas')),
                ('idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('idPrecio', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.Empresa')),
                ('idTipoPrueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.TipoPrueba')),
            ],
            options={
                'ordering': ['idEmpresa'],
                'unique_together': {('idEmpresa', 'idTipoPrueba')},
            },
        ),
    ]
